# Generated by Django 4.2.5 on 2023-09-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                default="578736d2-c0bb-4b04-a7b7-4e8409dd42c7",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.role",
            ),
            preserve_default=False,
        ),
    ]
