# Generated by Django 4.2.5 on 2023-09-14 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_confirm_email_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_id",
            new_name="id",
        ),
    ]
