# Generated by Django 4.2.5 on 2023-09-28 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["department_name"]},
        ),
    ]
