# Generated by Django 4.2.5 on 2023-09-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school_module", "0001_initial"),
        ("course_module", "0001_initial"),
        ("course_materials_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course_module.course"
            ),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school_module.school"
            ),
        ),
    ]
