# Generated by Django 4.2.5 on 2023-09-28 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_materials_module", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursematerial",
            options={"ordering": ["course_material_name"]},
        ),
    ]
