# Generated by Django 4.2.5 on 2023-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department_module", "0001_initial"),
        ("teacher_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teachers",
                to="department_module.department",
            ),
        ),
    ]
