# Generated by Django 4.2.5 on 2023-09-22 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(default="9c45e4", max_length=255),
                ),
                ("phone_number", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student_attendance",
            fields=[
                (
                    "attendance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attendance_status", models.CharField(max_length=255)),
                ("attendance_date", models.DateField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student_grade",
            fields=[
                (
                    "student_grade_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("grade", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grade_file",
                    models.FileField(
                        blank=True, null=True, upload_to="student_grades/%Y/%m/%d/"
                    ),
                ),
                (
                    "grade_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grade_level",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submit_assignment",
            fields=[
                (
                    "submit_assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "submit_assignment_file",
                    models.FileField(upload_to="submit_assignments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
