# Generated by Django 4.2.5 on 2023-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_module", "0003_alter_student_student_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="6b4a84", max_length=255),
        ),
    ]
