# Generated by Django 4.2.5 on 2023-09-18 00:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_module", "0003_assignment"),
        ("course_module", "0002_alter_course_department_alter_course_teacher"),
        ("department_module", "0001_initial"),
        ("school_module", "0001_initial"),
        (
            "student_module",
            "0005_submitassignment_assignment_submitassignment_course_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentGrade",
            new_name="Student_grade",
        ),
        migrations.RenameModel(
            old_name="SubmitAssignment",
            new_name="Submit_assignment",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="53122f", max_length=255),
        ),
        migrations.CreateModel(
            name="Student_attendance",
            fields=[
                (
                    "attendance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attendance_status", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_module.course",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_module.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_module.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_module.teacher",
                    ),
                ),
            ],
        ),
    ]
