# Generated by Django 4.2.5 on 2023-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_module", "0006_rename_studentgrade_student_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_grade",
            name="department",
        ),
        migrations.RemoveField(
            model_name="submit_assignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="submit_assignment",
            name="department",
        ),
        migrations.RemoveField(
            model_name="submit_assignment",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student_attendance",
            name="attendance_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="3ab87d", max_length=255),
        ),
        migrations.AlterField(
            model_name="student_grade",
            name="grade",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="student_grade",
            name="grade_file",
            field=models.FileField(blank=True, null=True, upload_to="student_grades"),
        ),
    ]
