# Generated by Django 4.2.5 on 2023-09-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_module", "0007_remove_student_grade_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="c3f7fe", max_length=255),
        ),
        migrations.AlterField(
            model_name="student_grade",
            name="grade_level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student_grade",
            name="grade_remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
