# Generated by Django 4.2.5 on 2023-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_module", "0003_assignment"),
        ("student_module", "0008_alter_student_student_id_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="student_attendance",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="student_grade",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="students",
                to="teacher_module.teacher",
            ),
        ),
        migrations.AddField(
            model_name="student_attendance",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="attendance_students",
                to="teacher_module.teacher",
            ),
        ),
        migrations.AddField(
            model_name="student_grade",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="grade_students", to="teacher_module.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="485178", max_length=255),
        ),
        migrations.AlterField(
            model_name="student_grade",
            name="grade_file",
            field=models.FileField(
                blank=True, null=True, upload_to="student_grades/%Y/%m/%d/"
            ),
        ),
    ]
