# Generated by Django 4.2.5 on 2023-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_module", "0010_alter_student_school_alter_student_student_id_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course",
            new_name="courses",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="24f4fb", max_length=255),
        ),
    ]
