# Generated by Django 4.2.5 on 2023-09-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_module", "0012_alter_student_student_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id_number",
            field=models.CharField(default="8fbc1c", max_length=255),
        ),
    ]
