# Generated by Django 4.2.5 on 2023-09-28 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["role_name"]},
        ),
    ]
