# Generated by Django 4.2.5 on 2023-09-13 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "school_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("school_name", models.CharField(max_length=255, unique=True)),
                ("school_email", models.EmailField(max_length=254, unique=True)),
                ("school_phone_number", models.CharField(max_length=255)),
                (
                    "school_licence_number",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "school_licence_certificate",
                    models.FileField(upload_to="licence_certificates/"),
                ),
                ("school_logo", models.ImageField(upload_to="school_logos/")),
                ("school_address", models.CharField(max_length=255)),
                ("school_city", models.CharField(max_length=255)),
                ("school_state", models.CharField(max_length=255)),
                ("school_postal_code", models.CharField(max_length=255)),
                ("school_country", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["school_name"],
            },
        ),
    ]
