# Generated by Django 4.2.5 on 2023-09-17 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("department_module", "0001_initial"),
        ("school_module", "0001_initial"),
        ("teacher_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("course_name", models.CharField(max_length=255, unique=True)),
                ("course_code", models.CharField(max_length=255, unique=True)),
                ("course_description", models.TextField()),
                ("course_credit", models.IntegerField()),
                ("course_duration", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ManyToManyField(
                        related_name="courses", to="department_module.department"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_module.school",
                    ),
                ),
                (
                    "teacher",
                    models.ManyToManyField(
                        related_name="courses", to="teacher_module.teacher"
                    ),
                ),
            ],
        ),
    ]
