# Generated by Django 4.2.5 on 2023-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teacher_module", "0001_initial"),
        ("course_module", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="courses",
                to="teacher_module.teacher",
            ),
        ),
    ]
