# Generated by Django 4.2.5 on 2023-09-25 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_module", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="department",
            new_name="departments",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="teacher",
            new_name="teachers",
        ),
    ]
